README.md
android/src/main/java/com/getcapacitor/community/admob/AdMob.java
ios/Plugin/Plugin.swift

Banner & Interstitial share the same listener so we can't define specific action for each. 
Also, It solve a bug on iOS where interstitial event are not fired (tested on iOS 14)

Separate Listener for Banner & Interstitial

---

README.md
ios/Plugin/Plugin.swift

The demo ad id for interstitial is using the demo id for banners.
https://developers.google.com/admob/android/test-ads
This will fix this error while using the isTesting: true for interstitial ads.
`Ad unit doesn't match format. <https://support.google.com/admob/answer/9905175#4>`

fix: fix interstitial ad id

---

android/src/main/java/com/getcapacitor/community/admob/executors/BannerExecutor.java

This is my first pull request to the open-source community, so if I made a mistake I am sorry and open to suggestions.

Fix: Android: AdPosition.BOTTOM_CENTER is not centered (#44)

---

ios/Plugin/Plugin.swift
ios/Podfile

The iOS build currently doesn't work because of breaking changes in the admob-sdk.
This PR resolves the breaking changes with reference to the migration guide: https://developers.google.com/admob/ios/migration#v8
This closes #66

iOS: migrate to new admob sdk

---

ios/Plugin/Plugin.swift

- Fixed onInterstitialAdClosed and onInterstitialAdOpened events for iOS
- Throw error in iOS showInterstitial method if the ad is not ready, to be consistent with the Android version
This is a fix for issue https://github.com/capacitor-community/admob/issues/82

Fixed event handlers for iOS interstitial ads

---

README.md
android/src/main/java/com/getcapacitor/community/admob/models/AdOptions.java
android/src/main/java/com/getcapacitor/community/admob/rewarded/AdRewardExecutor.java
android/src/main/java/com/getcapacitor/community/admob/rewarded/RewardedAdCallbackAndListeners.kt
android/src/main/java/com/getcapacitor/community/admob/rewarded/models/SsvInfo.kt
android/src/test/java/com/getcapacitor/community/admob/models/AdOptionsTest.java
android/src/test/java/com/getcapacitor/community/admob/rewarded/RewardedAdCallbackAndListenersTest.kt
ios/Plugin/Rewarded/AdRewardExecutor.swift
package.json
src/reward/index.ts
src/reward/reward-ad-options.interface.ts
src/reward/reward-definitions.interface.ts

Currently still to test with production ads on Android, as my AdMob says there aren't any Ads available at the moment. Once tested i can confirm it is working on both platforms. Android code may require some changes to fall more in line with the current code style. I don't know Swift/Java but have had more success implementing the iOS code over the Java code.
Feedback is welcome 😃 
Closes #107 on merge.

Feature: Support SSV on Rewarded Ads - Implements SSV Code

---

README.md

With Capacitor 4 the plugins should be registered **before** calling `super.onCreate(savedInstanceState);`.
See: [Updating from Capacitor 3 to Capacitor 4](https://capacitorjs.com/docs/updating/4-0#change-registerplugin-order)

docs(README): change registerPlugin order

---

android/build.gradle

update the `androidx.coordinatorlayout:coordinatorlayout` dependency to use the `$androidxCoordinatorLayoutVersion` variable.
set's the default value to 1.2.0 as that's the default capacitor uses.
Shouldn't be breaking since the demo app is using 1.2.0

refactor: Use androidxCoordinatorLayoutVersion variable

---

README.md
demo/angular/android/app/src/main/java/io/ionic/starter/MainActivity.java

Capacitor 3 introduced the automatic plugin registration, so calling `registerPlugin` is not needed and even discouraged.
`registerPlugin` is only used for local plugins not published on npm.
I've removed the step on the README and also the call on the demo app and the app keeps working as expected.

docs: Remove registerPlugin step

---

README.md
android/build.gradle

To prevent conflicts with other plugins and/or allowing users to use a newer `com.google.android.gms:play-services-ads` version without the need of updating the plugin.

feat(android): Add playServicesAdsVersion variable

---

ios/Plugin/Banner/BannerExecutor.swift
ios/Plugin/Interstitial/AdInterstitialExecutor.swift
ios/Plugin/Rewarded/AdRewardExecutor.swift

Instead of getting the rootViewController, use the plugin's viewController, should be the same on regular Capacitor apps
closes https://github.com/capacitor-community/admob/issues/183

refactor(ios): Use plugin viewController instead of rootViewController

---

ios/Plugin/Banner/BannerExecutor.swift
ios/Plugin/Interstitial/AdInterstitialExecutor.swift
ios/Plugin/Rewarded/AdRewardExecutor.swift

Reverts capacitor-community/admob#203
Primary: https://github.com/capacitor-community/admob/pull/204

Revert "refactor(ios): Use plugin viewController instead of rootViewController"

---

ios/Plugin/Banner/BannerExecutor.swift
ios/Plugin/Interstitial/AdInterstitialExecutor.swift
ios/Plugin/Plugin.swift
ios/Plugin/Rewarded/AdRewardExecutor.swift

Alternative to https://github.com/capacitor-community/admob/pull/203
Get the rootViewController without using the deprecated keyWindow and considering apps that use scenes with a helper getRootVC method in the Admob class, since the code is very complex to use it everywhere the rootViewController is needed.
closes https://github.com/capacitor-community/admob/issues/183

refactor(ios): get rootViewController considering scenes

---

README.md
android/src/main/java/com/getcapacitor/community/admob/AdMob.java
demo/angular/src/app/app.component.ts
ios/Plugin/Plugin.m
ios/Plugin/Plugin.swift
src/definitions.ts
src/web.ts

Adds methods for setApplicationMuted and setApplicationVolume, implementing #50. The simplest option to me seemed to be simply exposing the AdMob APIs directly here
I can't really figure out how the tests are setup (and they're barely necessary given the simplicity of these changes), so I'd appreciate if someone else could work those in. 
Otherwise, all tests that passed with version 4.1.0 are working with this PR. Version 4.1.0 had 2 failed tests, ShowInterstitial. Should not try to call show when no Interstitial was prepared, and ShowRewardVideoAd. Should not try to call show when no Reward was prepared. These still fail with this PR (at least on my device), but none of the code related to either of these tests or methods has been changed (ie, not a regression)
Otherwise, I believe I'd …

Add setApplicationMuted and setApplicationVolume methods

---

README.md
android/build.gradle

since next release is going to be a major update, it would be a good moment to update the play services ads dependency to latest
Also added `androidxCoreKTXVersion` variable to match other capacitor plugins that use `androidx.core:core-ktx` dependency.

feat!: Update play services ads dependency

---

.github/workflows/validation.yml

Capacitor 5 requires node 16, so I've updated the ci to use node 16
also updated all actions to use v3
removed the test step since there is no test script in the package.json, with v2 it was erroring but not failing the step, with v3 it fails

chore(ci): Update actions to use node 16

---

.github/workflows/validation.yml

Capacitor 5 requires java 17 and android tests is failing because of that
won't fix the tests because they were broken before, but will make them fail where they were failing before

chore(ci): Use java 17

---

ios/Plugin/Banner/BannerExecutor.swift

Fixing https://github.com/capacitor-community/admob/issues/160
iOs banner overlapping content on iPhone with rounded corners
iPhones with rounded corners appeared 12 sept of 2018
Since that release date iOs "view" gives a "safeAreaLayoutGuide"

For fixing issue #160 iOs banner overlapping content on iPhone

---

android/src/main/java/com/getcapacitor/community/admob/banner/BannerExecutor.java

This fix, considers the device full width during full screen landscape mode, to correctly align the banner ad to the center.
Issue #270

Android banner ads, fix center align in fullscreen, landscape mode.

---

ios/Plugin/Banner/BannerExecutor.swift
ios/Plugin/Consent/ConsentExecutor.swift
ios/Plugin/Interstitial/AdInterstitialExecutor.swift
ios/Plugin/Plugin.swift
ios/Plugin/Rewarded/AdRewardExecutor.swift
ios/PluginTests/PluginTests.swift
package.json

`autocorrect` was replaced by `--fix` long ago, so fmt and the commit hook were doing nothing on swift files.
This PR fix the fmt and swift files hook scripts and run fmt to apply missing changes.

chore: fix fmt script and run it

---

Package.swift

branch 6.0.0 doesn't exist, the proper way of setting the version is using `from`.
on the Capacitor 7 PR you sent it's been taken care of by the migration tool, but in case you want to fix it for the Capacitor 6 version too.

fix: use proper Capacitor 6 SPM dependency syntax

---

README.md

~~NOTE: I only deleted [LOC 414](https://github.com/capacitor-community/admob/blob/master/README.md?plain=1#L414) but the commit is strangely showing 993 additions and 991 deletions. I'm guessing this is issues with Windows/macOS/Linux end-of-line (EOL).~~
[requestTrackingAuthorization](https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/requesttrackingauthorization(completionhandler:)) is **NOT DEPRECATED** and has no direct relation to Google's UMP.
Here's a better explanation by ChatGPT:
- **Who requires it**: Apple
- **API**: `ATTrackingManager.requestTrackingAuthorization(completionHandler:)`
- **What it covers**:
- Whether your app can access the **IDFA** (Identifier for Advertisers) for personalized ads.
- Whether you can track users across **apps …

Fix misleading documentation

---

src/definitions.ts

In https://github.com/capacitor-community/admob/pull/369 this line was removed from the `README.md` file, but it's autogenerated from the types, so it gets re added on every `npm run build`.
This PR removes the line from the types so it doesn't get added.

docs: remove original misleading documentation

---

ios/Sources/AdMobPlugin/Banner/BannerExecutor.swift

The plugin supports iOS 14+, so the check is always true so the check and the else code can be removed

refactor(ios): Remove iOS 11 code check in BannerExecutor.swift
